# Generated by Django 3.1 on 2020-08-13 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_business_type',
            fields=[
                ('business_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('business_type', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_decision_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type_id', models.CharField(max_length=3)),
                ('decision_type', models.CharField(max_length=3)),
                ('type_pattern', models.CharField(max_length=3)),
                ('category_a', models.SmallIntegerField()),
                ('category_b', models.SmallIntegerField()),
                ('category_c', models.SmallIntegerField()),
                ('category_d', models.SmallIntegerField()),
                ('category_e', models.SmallIntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_employment_type',
            fields=[
                ('employment_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('employment_type', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_job_type',
            fields=[
                ('job_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_result',
            fields=[
                ('criteria', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('item_no', models.SmallIntegerField()),
                ('feature_group_id', models.SmallIntegerField()),
                ('feature_group_top', models.CharField(max_length=20)),
                ('feature_group_bottom', models.CharField(max_length=20)),
                ('feature_detail_id', models.SmallIntegerField()),
                ('feature_detail_top', models.CharField(max_length=20)),
                ('feature_detail_bottom', models.CharField(max_length=20)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('display_flag', models.BooleanField(blank=True, null=True)),
                ('terms', models.TextField(max_length=400)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_category_e', models.SmallIntegerField()),
                ('points_category_c', models.SmallIntegerField()),
                ('points_category_a', models.SmallIntegerField()),
                ('points_category_b', models.SmallIntegerField()),
                ('points_category_d', models.SmallIntegerField()),
                ('exam_date', models.DateField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('decision_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_decision_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.SmallIntegerField(blank=True, null=True)),
                ('percentile', models.SmallIntegerField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='M_question',
            fields=[
                ('question_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=50)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_result')),
            ],
        ),
        migrations.CreateModel(
            name='L_issued_password',
            fields=[
                ('issue_datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('one_time_password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('usage', models.BooleanField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='L_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name_kana', models.CharField(max_length=50)),
                ('first_name_kana', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('final_education', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation', models.DateField(blank=True, null=True)),
                ('last_career', models.CharField(blank=True, max_length=100, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_business_type')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_employment_type')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_job_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.SmallIntegerField()),
                ('delete_flag', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygtestapp.m_question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
